// Live Sports hub page layout — widgets tree for action:'layout'.

function liveSportsKindIcons() {
  return {
    football: 'soccer',
    soccer: 'soccer',
    fifa: 'soccer',
    'premier-league': 'soccer',
    'la-liga': 'soccer',
    'serie-a': 'soccer',
    bundesliga: 'soccer',
    'american-football': 'football',
    nfl: 'football',
    ncaaf: 'football',
    basketball: 'basketball',
    nba: 'basketball',
    ncaab: 'basketball',
    wnba: 'basketball',
    baseball: 'baseball',
    mlb: 'baseball',
    hockey: 'hockey',
    nhl: 'hockey',
    tennis: 'tennis',
    tenis: 'tennis',
    atp: 'tennis',
    cricket: 'cricket',
    krykiet: 'cricket',
    ipl: 'cricket',
    rugby: 'rugby',
    nrl: 'rugby',
    afl: 'rugby',
    'australian-football': 'rugby',
    golf: 'golf',
    volleyball: 'volleyball',
    volley: 'volleyball',
    handball: 'handball',
    wrestling: 'mma',
    wwe: 'mma',
    ufc: 'mma',
    mma: 'mma',
    boxing: 'mma',
    fight: 'mma',
    combat: 'mma',
    'combat-sports': 'mma',
    martial: 'mma',
    motor: 'motorsport',
    motorsport: 'motorsport',
    racing: 'motorsport',
    f1: 'motorsport',
    nascar: 'motorsport',
    formula: 'motorsport',
    dart: 'darts',
    darts: 'darts',
    snooker: 'billiards',
    billiard: 'billiards',
    pool: 'billiards',
    '8-ball': 'billiards',
    swim: 'swim',
    aquatic: 'swim',
    ski: 'ski',
    snow: 'ski',
    winter: 'ski',
    esport: 'esports',
    esports: 'esports',
    'e-sport': 'esports',
    gaming: 'esports',
    '24-7': 'tv',
    '24/7': 'tv',
    'live-tv': 'tv',
    livetv: 'tv',
    'tv-show': 'tv',
    stream: 'tv',
    other: 'sports',
    misc: 'sports',
    general: 'sports',
  };
}

function liveSportsCatalogActions() {
  return [
    {
      id: 'catalog',
      label: 'Catalog',
      icon: 'filter',
      dynamicCatalogs: true,
      default: 'all',
      // Host remaps chips when these revision tokens bump (install/remove Live addons).
      deps: ['stremio'],
      items: [
        { id: 'all', label: 'All' },
      ],
    },
    {
      id: 'horizon',
      label: 'Schedule',
      icon: 'schedule',
      // Host Status×Horizon sheet — never key off bare id alone.
      dynamicSchedule: true,
      default: 'airing|1h',
      items: [
        { id: 'airing|1h', label: 'Airing' },
        { id: 'upcoming|1h', label: 'Next · 1h' },
        { id: 'upcoming|3h', label: 'Next · 3h' },
        { id: 'upcoming|6h', label: 'Next · 6h' },
        { id: 'upcoming|24h', label: 'Next · 24h' },
        { id: 'both|1h', label: '1h' },
        { id: 'both|3h', label: '3h' },
        { id: 'both|6h', label: '6h' },
        { id: 'both|24h', label: '24h' },
      ],
    },
    {
      id: 'refresh',
      label: 'Refresh',
      icon: 'refresh',
      action: 'refresh',
    },
    {
      id: 'search',
      label: 'Search',
      action: 'eventSearch',
      trailing: true,
      placeholder: 'Team, match, sport…',
    },
    {
      id: 'view',
      label: 'View',
      style: 'group',
      trailing: true,
      default: 'list',
      items: [
        { id: 'list', label: 'List', icon: 'list' },
        { id: 'cards', label: 'Cards', icon: 'cards' },
      ],
    },
    {
      id: 'portals',
      label: 'Portals',
      action: 'portals',
      hoistSource: 'live_schedule',
      trailing: true,
      width: 260,
    },
  ];
}

function liveSportsLayout() {
  return {
    pages: {
      live_sports: {
        focus: {
          enter: 'kind',
          restore: 'kind',
          restoreMode: 'remembered',
          pageBack: ['schedule', 'kind'],
        },
        widgets: [
          kitTopBody('page', { expand: true }, [
            kitTopBar('chrome', {
              // ↓ from Catalog / Portals restores last schedule row (not All).
              focusDown: 'schedule',
              actions: liveSportsCatalogActions(),
            }),
            kitCategoryBar('kind', {
              source: 'live_schedule',
              dynamic: true,
              default: 'all',
              items: [{ id: 'all', label: 'All', icon: 'grid' }],
              kindIcons: liveSportsKindIcons(),
              focusUp: 'chrome',
              focusDown: 'schedule',
            }),
            hubWithLoad(
              kitList('schedule', {
                style: 'list',
                open: 'panel',
                openSetting: 'matchOpen',
                expand: true,
                kindMenu: 'kind',
                catalogMenu: 'catalog',
                horizonMenu: 'horizon',
                panelTab: 'providers',
                panelTabs: [
                  { id: 'providers', label: 'Providers', icon: 'dns' },
                  {
                    id: 'live_tv',
                    label: 'Live TV',
                    icon: 'tv',
                    browse: true,
                    action: 'liveTv',
                  },
                ],
                focusRight: 'sources-kind',
                emptyTitle: 'No matches in this schedule',
                emptyDescription: 'Try another catalog, horizon, or sport filter.',
              }),
              'feed',
              {},
            ),
          ]),
        ],
      },
    },
  };
}
